// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Data _$DataFromJson(Map<String, dynamic> json) => Data(
      aud: (json['AUD'] as num?)?.toDouble(),
      bgn: (json['BGN'] as num?)?.toDouble(),
      brl: (json['BRL'] as num?)?.toDouble(),
      cad: (json['CAD'] as num?)?.toDouble(),
      chf: (json['CHF'] as num?)?.toDouble(),
      cny: (json['CNY'] as num?)?.toDouble(),
      czk: (json['CZK'] as num?)?.toDouble(),
      dkk: (json['DKK'] as num?)?.toDouble(),
      eur: (json['EUR'] as num?)?.toDouble(),
      gbp: (json['GBP'] as num?)?.toDouble(),
      hkd: (json['HKD'] as num?)?.toDouble(),
      hrk: (json['HRK'] as num?)?.toDouble(),
      huf: (json['HUF'] as num?)?.toDouble(),
      idr: (json['IDR'] as num?)?.toDouble(),
      ils: (json['ILS'] as num?)?.toDouble(),
      inr: (json['INR'] as num?)?.toDouble(),
      isk: (json['ISK'] as num?)?.toDouble(),
      jpy: (json['JPY'] as num?)?.toDouble(),
      krw: (json['KRW'] as num?)?.toDouble(),
      mxn: (json['MXN'] as num?)?.toDouble(),
      myr: (json['MYR'] as num?)?.toDouble(),
      nok: (json['NOK'] as num?)?.toDouble(),
      nzd: (json['NZD'] as num?)?.toDouble(),
      php: (json['PHP'] as num?)?.toDouble(),
      pln: (json['PLN'] as num?)?.toDouble(),
      ron: (json['RON'] as num?)?.toDouble(),
      rub: (json['RUB'] as num?)?.toDouble(),
      sek: (json['SEK'] as num?)?.toDouble(),
      sgd: (json['SGD'] as num?)?.toDouble(),
      thb: (json['THB'] as num?)?.toDouble(),
      trys: (json['TRY'] as num?)?.toDouble(),
      usd: json['USD'] as int?,
      zar: (json['ZAR'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$DataToJson(Data instance) => <String, dynamic>{
      'AUD': instance.aud,
      'BGN': instance.bgn,
      'BRL': instance.brl,
      'CAD': instance.cad,
      'CHF': instance.chf,
      'CNY': instance.cny,
      'CZK': instance.czk,
      'DKK': instance.dkk,
      'EUR': instance.eur,
      'GBP': instance.gbp,
      'HKD': instance.hkd,
      'HRK': instance.hrk,
      'HUF': instance.huf,
      'IDR': instance.idr,
      'ILS': instance.ils,
      'INR': instance.inr,
      'ISK': instance.isk,
      'JPY': instance.jpy,
      'KRW': instance.krw,
      'MXN': instance.mxn,
      'MYR': instance.myr,
      'NOK': instance.nok,
      'NZD': instance.nzd,
      'PHP': instance.php,
      'PLN': instance.pln,
      'RON': instance.ron,
      'RUB': instance.rub,
      'SEK': instance.sek,
      'SGD': instance.sgd,
      'THB': instance.thb,
      'TRY': instance.trys,
      'USD': instance.usd,
      'ZAR': instance.zar,
    };
